# Generated by Django 4.2.1 on 2024-02-05 06:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_blogtagindexpage_blogpagetag_blogpage_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="blogpage",
            name="next_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the next page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="previous_page_relation",
                to="blog.blogpage",
            ),
        ),
        migrations.AddField(
            model_name="blogpage",
            name="previous_page",
            field=models.ForeignKey(
                blank=True,
                help_text="Select the previous page.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="next_page_relation",
                to="blog.blogpage",
            ),
        ),
    ]
